name = "suno-ai-proxy"
main = "src/index.ts"
compatibility_date = "2024-03-20"

[placement]
mode = "smart"

[vars]
SESSION_ID = "sess_2e8jvVr60P4h7wyinuwdd8Q8KjK"
ACCESS_TOKEN = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNsaWVudF8yZThqcTFJNzhXQXFkRnk5Y0taQkMybFJTcWsiLCJyb3RhdGluZ190b2tlbiI6InZ1bnd0dm1jcHFlNmQ3aHVnYWcyMTltNTE0MzVrdmc2eXl3Znh4MHMifQ.Xqmwh0T54H8RfSvV4-IEHk_lMtkJARwdgVDxHzEQp8F7uRwfQnknlemisNr8OT6Y8f4l9SdNFABQ2uDGg0jyT2bbIEotvrgYke6V94CZhe78u7qyuQOFgK2q7OQqfnxVEslKlf_DY7L9SJHPnWjX13B9b3a1l9hwUTxZNKOLyXWEVmMPZDm6eVeyADlw4HJOXmKsrqRioA_mCMkv8jaq4zM4pYyh42QMM8WMYoXMPJ81wIRgDSZ0ArHHYWg5RDTj4ugJbC2Vr38HMhB0tPyrK9XVF8_mJI68WmrLbm7mPfJa-0MOZ-aFdbAQrCVDT36A26JhuU05bpvk9tv46Cbl3g"



